apiVersion: v1
kind: Service
metadata:
  labels:
    service: project-fire
  name: project-fire
  namespace: msmb
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:543915562838:certificate/843ef189-844a-43f4-9ea9-ece04a342c22
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 443
      targetPort: 80
  selector:
    app: project-fire